language: node_js
node_js:
- 10
install:
    - yarn global add codecov
    - yarn --frozen-lockfile
cache: yarn
before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096
script:
- yarn run build-cs
- yarn run test-phy --silent
- yarn run test-cs --silent --coverage
- codecov
notifications:
  slack:
    rooms:
      secure: HXCxw9dS+BXmT7tWjRLukdo9vtritT+fmsA2YhG+wq1q34WBgdWpPwGBDLJWTFBRLurK22o5seOUetk8vFlDA+SYlpfjB7en/ykbUOgrOpNzU/AxnV53Eh1gNoU8D8+Ns3mRqTJ7duY5krMvme72PHRoZkBCuD27pF9VBBxRkJxAIXmDQqGprJv5Veu6jZZV3xGo12OkeVggXmnoCKUW/5U/uUUGs0Ptepy0ZH1Ud0HcEN+hP6bAp3OYQj3ccTIzhETxOr8p5fM6rAXNDDEMQArmINS6gFVQCBN9CkrFH6RaE1OMxU4ChVGxihw7o7AUqF7QTEAVh8545kYPPwIhGX+zttxceWvLKJf95lS8CejzEhNEoAdMk5I2CgoqkF4xJ1fw5VS0jkrcyvHMUBoMB4L2p4TKlysrakIVH1labyNDA2gJnxQ4QJ29pxBXxkUDKvfwBfAYcCCnt08ErkNLtsNauz+z6fd8DzdoWwIfu4Ci9wVnRL68dxza4vG4dBxWenAOazaFfPVXkWHduwLAYnncfzIUNth3EBdtQlPp2WxEHq/BAuqfaCVpw5g21tTDaBvW53fQkF9WIjRTEfVVbFficzjNUb3iJSo5fjzaDk/FtwJ0x8a3/pQjyMVpMGOrRpbCa3qu3W1klcW/eBE9movSYtrHzpOu7V2ovfm/I6M=