name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-and-test:
    name: Build, Lint and Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build application
      run: yarn build-cs
    - name: Run the linter
      run: yarn lint
    - name: Run tests (with code coverage)
      run: yarn test --coverage --coverageReporters json-summary
    - name: Print code coverage in PR
      uses: MishaKav/jest-coverage-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
