name: Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta cs
        id: meta-cs
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-cs
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
      - name: Docker meta cs-renderer
        id: meta-cs-renderer
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-cs-renderer
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
      - name: Build and push cs Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET=build-cs
          tags: ${{ steps.meta-cs.outputs.tags }}
          labels: ${{ steps.meta-cs.outputs.labels }}
      - name: Build and push cs-renderer Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET=build-cs-renderer
          tags: ${{ steps.meta-cs-renderer.outputs.tags }}
          labels: ${{ steps.meta-cs-renderer.outputs.labels }}
  